packages:
  - ui

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  ansi-html@<0.0.8: '>=0.0.8'
  braces@<3.0.3: '>=3.0.3'
  clean-css@<4.1.11: '>=4.1.11'
  json5@<1.0.2: '>=1.0.2'
  markdown-it@<12.3.2: '>=12.3.2'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<10.2.1: '>=10.2.1'
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tmp@<=0.2.3: '>=0.2.4'
